###

Get http://localhost:4004/v2/odata/v4/MaterialSrv/AuthUser?$filter=UserName eq 'emilydavis' and Password eq 'pass1234'

###
Get http://localhost:4004/odata/v4/MaterialSrv/MaterialMaster


### Crete new Material
POST http://localhost:4004/odata/v4/MaterialSrv/MaterialMaster
Content-Type: application/json

{
    "MaterialNumber":24,
    "Description":"Test Material",
    "IndustrySector":"001000",
    "MaterialType":"001001",
    "Plant":"PL01",
    "StorageLocation":"ST01",
    "UOM":"EA",
    "MaterialGroup":"MOHE"
}


